### ISSUE TITLE
A better admin panel

### ISSUE THREAD

**Issue by RupakBiswas-2304** [Anwesha-2k23/backend#69]
- We are using the default admin panel of the django 
- Make the admin panel user friendly, add some style

**Comment by DarK-VEnOM-16** [comment]
I would like to work on this

**Comment by pundarikaksha7** [comment]
Kindly assign

**Comment by DarK-VEnOM-16** [comment]
![image](https://user-images.githubusercontent.com/75152702/206909819-b857eee4-2b35-44c3-9b52-f127be74c16f.png)
It needs a Secret Key and there is no .env file

**Comment by RupakBiswas-2304** [comment]
I have updated the settings.py, please pull, and please implement on Local level, I can share AWS credentials, other env parameters are mentioned in README.md
